# Generated by Django 4.0 on 2021-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=35, max_digits=10),
        ),
        migrations.AlterField(
            model_name='bill',
            name='wasting_percentage',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=4),
        ),
    ]
